- name: debug
  debug:
    msg: "we will initialize the cluster"


- name: initilaize cluster
  command: kubeadm init --control-plane-endpoint {{vip}}:{{vip_port}} --upload-certs

# make kubectl work for root user on masternode
- name: Create ~/.kube directory
  file: 
    name: ~/.kube
    state: directory
    
- name: Populate .kube/config file
  copy: 
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    remote_src: yes

- include_tasks: 
   file: install_cni.yml